// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
#pragma warning disable CS9084 // Struct member returns 'this' or other instance members by reference



    namespace LibCRIComp
    {
        public unsafe static partial class CriCompression
        {
            [StructLayout(LayoutKind.Sequential, Size = 1)]
            public partial struct __Internal
            {
                [SuppressUnmanagedCodeSecurity, DllImport("LibCRIComp", EntryPoint = "_ZN10LibCRIComp14CriCompression11CRIcompressEPhPiS1_i", CallingConvention = __CallingConvention.Cdecl)]
                internal static extern int CRIcompress(byte* dest, int* destLen, byte* src, int srcLen);
            }

            public static int CRIcompress(byte* dest, ref int destLen, byte* src, int srcLen)
            {
                fixed (int* __destLen1 = &destLen)
                {
                    var __arg1 = __destLen1;
                    var ___ret = __Internal.CRIcompress(dest, __arg1, src, srcLen);
                    return ___ret;
                }
            }
        }
    }

